import LanguagePlugin from '../../LanguagePlugin'

class Finnish extends LanguagePlugin {

  static code = 'Finnish'
  static title = 'Finnish'
  static version = '1.0'
  static icon = 'Flag'
  static releaseDate = '2021-05-09'
  static use = 'ui'
  static type = 'language'
  static description = 'Finnish translation of the application.'

  static languages = {
    fi: {
      '{{count}} transactions': '{{count}} tapahtumaa',
      '1 transaction': '1 tapahtuma',
      'Account Balances': 'Tilien saldot',
      'Account name is required.': 'Tilin nimi puuttuu.',
      'Account Name': 'Tilin nimi',
      'Account number exists.': 'Tilin numero on jo käytössä.',
      'Account number is required.': 'Tilin numero puuttuu.',
      'Account Number': 'Tilin numero',
      'Account scheme': 'Tilikartta',
      'Account type is required.': 'Tilin laji puuttuu.',
      'Account Type': 'Tilin laji',
      'Account VAT': 'Tilin ALV',
      'Admin Tools': 'Ylläpitotyökalut',
      'Business ID': 'Y-tunnus',
      'Business name': 'Yrityksen nimi',
      'Cannot be negative.': 'Ei voi olla negatiivinen.',
      'Cannot edit this entry. Period locked?': 'Muokkaaminen ei onnistu. Onko kausi lukittu?',
      'Company Info': 'Yrityksen tiedot',
      'Company name is required.': 'Yrityksen nimi puuttuu.',
      'Company Name': 'Yrityksen nimi',
      'Company Registration Number': 'Y-tunnus',
      'Create New Account': 'Luo uusi tili',
      'Create New User': 'Luo uusi käyttäjä',
      'Cumulated VAT by tags': 'Kertynyt ALV tägeittäin',
      'Cumulated VAT from purchases': 'Kertynyt ALV ostoista',
      'Cumulated VAT from sales': 'Kertynyt ALV myynnistä',
      'Current VAT payable': 'Nykyiset ALV velat',
      'Current VAT receivable': 'Nykyiset ALV saatavat',
      'Database Management': 'Tietokantojen hallinta',
      'Database name is required.': 'Tietokannan nimi puuttuu.',
      'Database Name': 'Tietokannan nimi',
      'Date is after the current period ends.': 'Päiväys on nykyisen tilikauden jälkeen.',
      'Date is before the current period starts.': 'Päiväys on ajalta ennen kuin nykyinen tilikausi alkaa.',
      'Date is incorrect.': 'Virheellinen päivämäärä.',
      'Debit and credit do not match': 'Debet ja kredit ei täsmää',
      'Delayed VAT': 'Siirretty ALV',
      'Delete Account': 'Poista tili',
      'Delete these transactions?': 'Poistetaanko namä tapahtumat?',
      'Delete this account?': 'Poistetaanko tämä tili?',
      'Delete this transaction?': 'Poistetaanko tämä tapahtuma?',
      'Edit Account': 'Muokkaa tiliä',
      'Email is required.': 'Sähköpostiosoite puuttuu.',
      'End Date': 'Loppuu',
      'Entries that has no tags': 'Tapahtumat, joissa ei ole yhtään tägiä',
      'Full name is required.': 'Käyttäjän koko nimi puuttuu.',
      'Full Name': 'Koko nimi',
      'Initial balance': 'Alkusaldo',
      'Invalid credentials.': 'Kirjautuminen epäonnistui.',
      'Invalid database name.': 'Tietokannan nimi ei kelpaa.',
      'Mark as a favorite': 'Merkise suosikiksi',
      'No account selected': 'Ei valittua tiliä',
      'No Database Selected': 'Ei valittua tietokantaa',
      'No such account found.': 'Tiliä ei ole olemassa.',
      'No Tools': 'Ei työkaluja',
      'no transactions': 'ei tapahtumia',
      'No User Selected': 'Ei valittua käyttäjää',
      'Note that a database with the same name is overridden automatically.': 'Huomaa, että jos samanniminen tietokanta on jo olemassa, se ylikirjoitetaan automaattisesti.',
      'Numeric value incorrect.': 'Virheellinen numeroarvo.',
      'Password Again': 'Salasana uudelleen',
      'Password is too short.': 'Salasana on liian lyhyt.',
      'Passwords do not match.': 'Salasanat ei täsmää.',
      'Payable to add': 'Lisättävä velkaa',
      'period {{period}}': 'tilikausi {{period}}',
      'Please register an admin user': 'Ole hyvä ja syötä pääkäyttäjän tiedot',
      'Please select an account': 'Ole hyvä ja valitse tili',
      'Plugin Tools': 'Lisäosien hallintatyökalut',
      'Press Insert to create a transaction.': 'Voit luoda tapahtuman painamalla Insert.',
      'Receivable to add': 'Lisättävä saatavia',
      'Remove favorite status': 'Poista suosikeista',
      'Saving failed.': 'Tallennus epäonnistui.',
      'Select database': 'Valitse kanta',
      'Select period': 'Valitse tilikausi',
      'Start Date': 'Alkaa',
      'Start new period?': 'Aloitetaanko uusi tilikausi?',
      'This database does not have configured VAT accounts.': 'Tässä tietokannassa ei ole konfiguroituna ALV-tilejä.',
      'This field is required.': 'Tämä kenttä ei voi olla tyhjä.',
      'This system has no admin user': 'Järjestelmästä puuttuu pääkäyttäjä',
      'Total lines': 'Rivejä yhteensä',
      'Transaction key account changed and moved out of this screen.': 'Aktiivinen tili muuttui ja koko tapahtuma siirtyi pois tältä sivulta',
      'Undefined tag.': 'Tägiä ei ole määritelty.',
      'Upload Database': 'Lähetä tiedosto',
      'User creation failed.': 'Käyttäjän luonti epäonnistui.',
      'User name is not valid (lower case letters and numbers only).': 'Käyttäjätunnus ei kelpaa (vain pienet kirjaimet ja numerot sallitaan)',
      'User Tools': 'Käyttäjien hallintatyökalut',
      'Value Added Tax': 'Arvonlisävero',
      'VAT %': 'ALV %',
      'VAT from purchases': 'ALV ostoista',
      'VAT from sales': 'ALV myynnistä',
      'VAT update': 'ALV päivitys',
      'You can upload backup file here.': 'Voit lähettää tästä olemassaolevan varmuuskopion.',
      Account: 'Tili',
      Accounts: 'Tilit',
      Admin: 'Ylläpito',
      Balance: 'Saldo',
      Cancel: 'Peru',
      Confirm: 'Hyväksy',
      Credit: 'Kredit',
      Database: 'Tietokanta',
      Databases: 'Tietokannat',
      Date: 'Päiväys',
      Debit: 'Debet',
      Description: 'Kuvaus',
      Documents: 'Tositteet',
      Email: 'Sähköpostiosoite',
      Home: 'Alkuun',
      Import: 'Tuonti',
      Locked: 'Lukittu',
      Locking: 'Lukitus',
      Login: 'Kirjaudu',
      Logout: 'Poistu',
      Name: 'Nimi',
      No: 'Ei',
      Other: 'Muu',
      Password: 'Salasana',
      Periods: 'Tilikaudet',
      Plugins: 'Lisäosat',
      Publish: 'Julkaise',
      Reports: 'Raportit',
      Search: 'Etsi',
      Submit: 'Lähetä',
      Tools: 'Työkalut',
      Total: 'Yhteensä',
      Transactions: 'Tapahtumat',
      Unlocked: 'Auki',
      User: 'Käyttäjä',
      Username: 'Käyttäjätunnus',
      Users: 'Käyttäjät',
      View: 'Katso',
      Yes: 'Kyllä',

      'report-balance-sheet-detailed': 'Tase tilierittelyin',
      'report-balance-sheet': 'Tase',
      'report-general-journal': 'Päiväkirja',
      'report-general-ledger': 'Pääkirja',
      'report-income-statement-detailed': 'Tuloslaskelma tilierittelyin',
      'report-income-statement': 'Tuloslaskelma',

      'icon-add-tx': 'Lisää uusi tapahtuma',
      'icon-hide-details': 'Piilota osatapahtumat',
      'icon-show-details': 'Näytä osatapahtumat',
      'icon-show-all': 'Näytä kaikki',
      'icon-hide-all': 'Piilota kaikki',
      'icon-all-account-types': 'Valitse kaikki tyyppivalinnat',
      'icon-asset': 'Varat',
      'icon-create-period': 'Aloita uusi tilikausi',
      'icon-create-user': 'Luo uusi käyttäjä',
      'icon-download-csv': 'Lataa CSV-tiedostona',
      'icon-drop-empty-documents': 'Poista kaikki tyhjät tositteet',
      'icon-equity': 'Pääoma',
      'icon-expense': 'Menot',
      'icon-favorite': 'Suosikit',
      'icon-fix-vat-descriptions': 'Korjaa puuttuvat kuvaukset',
      'icon-liability': 'Velat',
      'icon-lock-period': 'Lukitse tilikausi',
      'icon-none-account-types': 'Poista kaikki tyyppivalinnat',
      'icon-option-byTags': 'Tägeittäin',
      'icon-option-compact': 'Tiivistetympi esitysmuoto',
      'icon-option-full': 'Koko vuosi',
      'icon-option-quarter1': 'Ensimmäinen neljännes',
      'icon-option-quarter2': 'Ensimmäinen puoli vuotta',
      'icon-option-quarter3': 'Kolme neljännestä',
      'icon-print': 'Tulosta',
      'icon-profit': 'Voitto',
      'icon-refresh-plugins': 'Päivitä lisäosalista',
      'icon-revenue': 'Tulot',
      'icon-sort-documents': 'Järjestä tositenumerot päivämääräjän mukaan',
      'icon-summarize-vat-period': 'Kerää ALV velat/saatavat',
      'icon-unlock-period': 'Poista tilikauden lukitus',
      'icon-upload-database': 'Lähetä palvelimelle varmuuskopiotiedosto',
      'icon-new-database': 'Luo uusi tietokanta',

      'column-account-number': 'Nro',
      'column-balance': 'Saldo',
      'column-credit': 'Kredit',
      'column-description': 'Kuvaus',
      'column-date': 'Päiväys',
      'column-date-and-accounts': 'Päiväys ja tilit',
      'column-debit': 'Debet',
      'column-document-number': 'Nro',
      'column-name-or-date': 'Tili / Päiväys',

      ASSET: 'Varat ja saatavat',
      LIABILITY: 'Velat',
      EQUITY: 'Pääoma',
      REVENUE: 'Tulot',
      EXPENSE: 'Menot',
      PROFIT_PREV: 'Edellisten tilikausien voitto',
      PROFIT: 'Voitto'
    }
  }

  flag(language) {
    return 'fi'
  }
}

export default Finnish
